apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mssql-data-01
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Gi 
  storageClassName: solidfire-gold
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mssql-backup-01
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Gi
  storageClassName: solidfire-gold
